# Generated by Django 3.0.4 on 2020-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(default=0, max_length=200)),
                ('subtenant_id', models.CharField(default=0, max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('data_source', models.CharField(choices=[('dcm', 'DCM'), ('facebook', 'FACEBOOK'), ('amnet', 'AMNET')], max_length=200)),
                ('do_events', models.BooleanField(default=False)),
                ('client_onboarding', models.BooleanField(default=False)),
                ('job_source', models.CharField(choices=[('azure', 'AZURE'), ('gcs', 'GOOGLE CLOUD STORAGE'), ('aws', 'AMAZON WEB SERVICES')], max_length=200)),
                ('schedule', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
