# Generated by Django 3.0.4 on 2020-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DagTrigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dag_id', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('mapping_set', models.BooleanField(default=False)),
                ('dag_triggered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MappingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(max_length=128, unique=True)),
                ('mapping_set', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('offset', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
            ],
        ),
    ]
